// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table clients {
  client_id integer [primary key]
  client_name varchar [not null]
  created_at timestamp 
}

// TODO: в будущем можно организовать составные маршруты из нескольких точек, что потребует переработки таблицы (добавление доп. таблиц)
Table orders {
  order_id integer [primary key]
  client_id integer [not null]
  start_latitude Numeric(6,5) // широта точки старта
  start_longitude Numeric(6,5) // долгота точки старта
  finish_latitude Numeric(6,5) // широта точки финиша
  finish_longitude Numeric(6,5) // долгота точки финиша
  price Numeric(18,2)
  created_at timestamp

  Indexes { 
    client_id
  }
}

Table order_status {
  id integer [primary key]
  order_id integer [not null]
  car_id integer 
  status varchar
  start_at timestamp
  finish_at timestamp
  unpaid_rest Numeric(18,2)
  created_at timestamp 
  Indexes { 
    order_id
  }
  Indexes { 
    car_id
  }

}

Table drivers {
  driver_id integer [primary key]
  driver_name varchar [not null]
  created_at timestamp
}

Table car_drivers {
  id integer [primary key]
  driver_id integer [not null]
  car_id integer [not null]
  fromdate date [not null]
  created_at timestamp 
  Indexes { 
    driver_id
  }
  Indexes { 
    car_id
  }
}

Table cars {
  car_id integer [primary key]
  model varchar
  color varchar
  production_date date
  vin_number varchar
  reg_number varchar [not null]
  created_at timestamp 
}

Table car_status {
  id integer [primary key]
  car_id integer [not null]
  status varchar
  current_latitude Numeric(6,5) // широта точки финиша
  current_longitude Numeric(6,5) // долгота точки финиша
  order_id integer // занятость водителя в поездке
  created_at timestamp  
  Indexes { 
    car_id
  }  
}


Ref: orders.client_id > clients.client_id 

Ref: order_status.order_id > orders.order_id 
Ref: order_status.car_id < cars.car_id 

Ref: car_drivers.car_id < cars.car_id 
Ref: car_drivers.driver_id < drivers.driver_id

Ref: car_status.car_id > cars.car_id
Ref: car_status.order_id - orders.order_id
